services:
  - type: web
    name: whisper-transcriber
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHON_MEMORY_LIMIT
        value: 512
    plan: free
    autoDeploy: false
    disk:
      name: whisper-data
      mountPath: /app/models
      sizeGB: 1 